### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Erucae** [Erucae/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by reserve-acc** [comment]
EXPERIENCE
2017
Became 45th president of the United States

2016
Won election race with 77 votes more than Clinton, yippe-kee-yay!

2015
Became the most important Republican nominating for presidential election run

2009
Changed my mind and became Republican again

2005
Started Trump University with Michael Sexton and Jonathan Spitalny: no grades, certificates and other bureaucracy, but program offered courses in real estate, asset management entrepreneurship, and wealth creation. 98% students gave positive reviews while studying, however some of these ungrateful gringos filed lawsuits against Trump University after the course. I had to pay $25 million to settle that...

2002
Acquired the former Hotel Delmonico, which was renovated and reopened in 2004 as the Trump Park Avenue. I sure do like my surname!

2001
Completed Trump World Tower and joined the Democratic Party

1999
Started buying golf courses. They are very cheap, I have 18 of them now in USA and abroad! Also switched to the Reform Party that year

1997
Began a multi-building development along the Hudson River, which was named Trump Place. Me and the other investors sold our shares for $1.8 billion and that was then the biggest residential sale in the history of New York City

1996
Acquired the Bank of Manhattan Trust Building, which was a vacant seventy-one story skyscraper on Wall Street. After an extensive renovation, the high-rise was renamed the Trump Building

1994
Refurbished the Gulf and Western Building on Columbus Circle, turned it into a 44-story luxury property known as Trump International Hotel and Tower

1989 ― 1992
Ran a second hand airline called Trump Shuttle. What a waste of money, I had to sell it, now it is American Airlines Shuttle, btw

1989, 1990
Learned about Tour de France and decided to hold my very own Tour de Trump. Is America not great enough for that cycling competition?

1988
Acquired the Plaza Hotel in Manhattan for $407 million, invested $50 million to restore the building and boosted it from three-star to four-star hotel (I called it "the Mona Lisa" and sold it for a lot of cash in 1995)

1987
Registered as a Republican

1985
I bought the Mar-a-Lago estate in Palm Beach and turned it into a private club.You can join if you pay $200K initiation fee (and there is another annual fee for members, it is very expensive to be rich). That year I also opened a casino called Trump Castle. My wife Ivana became a manager, because she is another Trump!

1983
I purchased New Jersey Generals, an American football team. I changed team's play schedule and filed an antitrust lawsuit against United States Football League, so NJG are not doing so good now, but back then they were great!

1980
Started developing the Trump Tower skyscraper in Manhattan, I payed a crew of undocumented Polish workers to demolish the historic Bonwit Teller store, including art deco features. All this to make architectural critic Paul Goldberger say in 1983 that the tower's atrium is "the most pleasant interior public space to be completed in New York in some years". At the same time I also started a repair job on the Wollman Rink in Central Park and completed the work in three months for $1.95 million, which was $775,000 less than the initial budget!

1978
Purchased a 50 percent stake in the derelict Commodore Hotel and turned it into the Grand Hyatt Hotel in 2 years of remodeling

1971
Was promoted to president of the company and renamed it The Trump Organization

1968
Began my career at my father's real estate development company, Elizabeth Trump & Son

PERSONAL LIFE
2006
Melania gained United States citizenship and gave birth to our son, Barron

2005
Married her

1998
Met my future third wife, Melania Knauss

1999
Divorced Marla ¯_(ツ)_/¯

1993
Married Marla and had a daughter, we named her Tiffany, because I like Tiffany & Company jewellery as well

1992
Started affair with Marla Maples, so I had to divorce. God knows I love nice women, I love them all!

1984
Birth of Eric Trump

1982
Birth of Ivanka Trump

1977
My first son is born. I called him Donald, of course!

1977
Married Czech model Ivana Zelníčková

MEDIA CAREER
2019
Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9"

2015
Published a book "Crippled America: How to Make America Great Again"

2011
Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver

2011
Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki

2011
Published a book "Trump Tower" in coauthorship with Jeffrey Robinson

2009
Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver

2008
Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver

2007
Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker

2007
Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant

2006
Published a book "Why We Want You to Be Rich" in coauthorship with Meredith McIver and Robert Kiyosaki

2006
Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"

2006
Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"

2006
Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver

2005
Published a book "The Best Golf Advice I Ever Received"

2005
Performed a song with Megan Mullally at the 57th Primetime Emmy Awards

2004 ― 2008
Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)

2004
Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver

2004
Published a book "The Way to the Top: The Best Business Advice I Ever Received"

2004
Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver

2003 ― 2015
Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"

2000
Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett

1997
Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner

1991
Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"

1990
Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen

1987
Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz

EDUCATION
2011
Asked friends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!

1966
Transferred to the Wharton School of the University of Pennsylvania and graduated in May 1968 with a B.S. in economics

1964
Started studying in Fordham University

1959
Enrolled in the New York Military Academy, a private boarding school, after my parents discovered I made frequent trips into Manhattan without their permission
